FROM okatsn/my-tex-life:v2024a1

USER root

USER $NB_UID

# RUN rm -rf $VSCODE_PATH && \
#     mkdir -p $VSCODE_PATH/extensions \
#     $SUB_PROJECT_DIR \
#     && chown -R $NB_USER:$NB_GID \
#     $VSCODE_PATH


