# # Instruction
# - assign a new image name
# - make this file consistent with that in https://github.com/okatsn/MyTeXLife
version: "3.2"

services:
  dev_chaos2019:
    build:
      context: ..
      #     That is out of /.devcontainer
      # context: .
      #     That is /.devcontainer
      dockerfile: .devcontainer/Dockerfile
      args:
        JULIA_PKG_DEVDIR: /home/jovyan/.julia/dev # just let it be default. See [JULIA_PKG_DEVDIR](https://docs.julialang.org/en/v1/manual/environment-variables/#JULIA_PKG_DEVDIR). Be aware that some tests will depend on JULIA_PKG_DEVDIR.
        # SUB_PROJECT_DIR is defined in my-tex-life
    image: chaos2019
    init: true
    # See https://docs.docker.com/compose/compose-file/compose-file-v3/#init
    container_name: dev-chaos2019
    volumes:
      # # The home directory is called "workspace"; try `cd ..` and `ls` to figure it out.
      - ../:/workspace
      # # Docker socket to access Docker server
      - /var/run/docker.sock:/var/run/docker.sock
      # # SSH directory
      - ~/.ssh:/home/jovyan/.ssh
      # For Windows without WSL, a copy will be made from /tmp/.ssh to ~/.ssh to fix permissions
      # - ~/.ssh:/tmp/.ssh:ro
      # # Shell history persistence
      - ~/.zsh_history:/home/jovyan/.zsh_history:z
      # # Git config
      - ~/.gitconfig:/home/jovyan/.gitconfig
      # # Persistent volumes for this container; Avoid reinstall vscode extensions
      - julia-depot:/home/jovyan/.julia
      # # KEYNOTE: 
      # # - Named volumes is chosen because VSCode extensions of this environment is not expected to be shared with those in WSL.
      # # - Please refer to okatsn/MyTeXLife for more explanation
      - vscode-server:/home/jovyan/.vscode-server


    environment:
      - TZ=TW
      # Set time zone
      # entrypoint: ["zsh", "-c", "while sleep 1000; do :; done"]
    entrypoint: sh -c "sleep infinity"
# KEYNOTE: Those defined volumes in service should be declared in the root level
# Unbind vscode-server to volumes to ensure extensions in devcontainer.json to be installed on rebuild
volumes:
  julia-depot:
  vscode-server:
